---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare
  namespace: traefik
type: Opaque
stringData:
  api-token: ${K3S_TRAEFIK_CLOUDFLARE_TOKEN}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare
  namespace: traefik
spec:
  acme:
    email: ${K3S_TRAEFIK_CLOUDFLARE_EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-key
    solvers:
      - dns01:
          cloudflare:
            email: ${K3S_TRAEFIK_CLOUDFLARE_EMAIL}
            apiTokenSecretRef:
              name: cloudflare
              key: api-token