apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
  namespace: default
spec:
  secretName: certificate-tls
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - '${K3S_CERTMGR_CLOUDFLARE_DNS1}'
    - '${K3S_CERTMGR_CLOUDFLARE_DNS2}'