apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer 
spec:
  acme:
    email: ${K3S_CERTMGR_CLOUDFLARE_EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-issuer-key
    solvers:
    - dns01:
        cloudflare:
          email: ${K3S_CERTMGR_CLOUDFLARE_EMAIL}
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token